name: alphanum_comparator
description: A new Flutter package project.
version: 0.0.1
author: Quantos
homepage: https://github.com/quantosapplications/dart_alphanum_comparator

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: